# client id and secret from https://developer.uber.com/dashboard/
client_id: "****"
client_secret: "****"
redirect_url: "http://localhost:8000/"
scopes:
    - profile
    - history
    - places
    - request
    - request_receipt
    - all_trips